// <auto-generated />
using ClasesEjercicioPrueba.Data1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClasesEjercicioPrueba.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250910231549_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClasesEjercicioPrueba.Models.Vehiculo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cantidadPuertas")
                        .HasColumnType("int");

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("motor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("tieneAuxiliar")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
